import { Phoneme } from '@/types'

export const initialPhonemesM: Phoneme[] = [
  { time: 25, type: 'word', start: 0, end: 2, value: 'Hi' },
  { time: 25, type: 'viseme', value: 'k' },
  { time: 87, type: 'viseme', value: 'a' },
  { time: 175, type: 'word', start: 3, end: 8, value: 'there' },
  { time: 175, type: 'viseme', value: 'T' },
  { time: 212, type: 'viseme', value: 'E' },
  { time: 312, type: 'viseme', value: 'r' },
  { time: 437, type: 'viseme', value: 'sil' },
  { time: 892, type: 'word', start: 10, end: 12, value: 'My' },
  { time: 892, type: 'viseme', value: 'p' },
  { time: 967, type: 'viseme', value: 'a' },
  { time: 1030, type: 'word', start: 13, end: 17, value: 'name' },
  { time: 1030, type: 'viseme', value: 't' },
  { time: 1092, type: 'viseme', value: 'e' },
  { time: 1155, type: 'viseme', value: 'p' },
  { time: 1205, type: 'word', start: 18, end: 20, value: 'is' },
  { time: 1205, type: 'viseme', value: 'i' },
  { time: 1255, type: 'viseme', value: 's' },
  { time: 1330, type: 'word', start: 21, end: 23, value: 'Zi' },
  { time: 1330, type: 'viseme', value: 's' },
  { time: 1417, type: 'viseme', value: 'i' },
  { time: 1742, type: 'viseme', value: 'sil' },
  { time: 2197, type: 'word', start: 25, end: 28, value: "I'm" },
  { time: 2197, type: 'viseme', value: 'a' },
  { time: 2285, type: 'viseme', value: 'p' },
  { time: 2347, type: 'word', start: 29, end: 30, value: 'a' },
  { time: 2347, type: 'viseme', value: '@' },
  { time: 2397, type: 'word', start: 31, end: 34, value: 'web' },
  { time: 2397, type: 'viseme', value: 'u' },
  { time: 2535, type: 'viseme', value: 'E' },
  { time: 2610, type: 'viseme', value: 'p' },
  { time: 2672, type: 'word', start: 35, end: 44, value: 'developer' },
  { time: 2672, type: 'viseme', value: 't' },
  { time: 2722, type: 'viseme', value: '@' },
  { time: 2760, type: 'viseme', value: 'f' },
  { time: 2810, type: 'viseme', value: 'E' },
  { time: 2847, type: 'viseme', value: 't' },
  { time: 2935, type: 'viseme', value: '@' },
  { time: 2972, type: 'viseme', value: 'p' },
  { time: 3060, type: 'viseme', value: 'E' },
  { time: 3122, type: 'word', start: 45, end: 50, value: 'based' },
  { time: 3122, type: 'viseme', value: 'p' },
  { time: 3197, type: 'viseme', value: 'e' },
  { time: 3335, type: 'viseme', value: 's' },
  { time: 3397, type: 'viseme', value: 't' },
  { time: 3460, type: 'word', start: 51, end: 53, value: 'in' },
  { time: 3460, type: 'viseme', value: 'i' },
  { time: 3497, type: 'viseme', value: 't' },
  { time: 3560, type: 'word', start: 54, end: 63, value: 'Melbourne' },
  { time: 3560, type: 'viseme', value: 'p' },
  { time: 3622, type: 'viseme', value: 'E' },
  { time: 3660, type: 'viseme', value: 't' },
  { time: 3760, type: 'viseme', value: 'p' },
  { time: 3835, type: 'viseme', value: 'O' },
  { time: 3972, type: 'viseme', value: 'r' },
  { time: 4022, type: 'viseme', value: 't' },
  { time: 4197, type: 'viseme', value: 'sil' },
  { time: 4385, type: 'word', start: 65, end: 74, value: 'Australia' },
  { time: 4385, type: 'viseme', value: 'O' },
  { time: 4472, type: 'viseme', value: 's' },
  { time: 4572, type: 'viseme', value: 't' },
  { time: 4635, type: 'viseme', value: 'r' },
  { time: 4685, type: 'viseme', value: 'e' },
  { time: 4710, type: 'viseme', value: 't' },
  { time: 4810, type: 'viseme', value: 'i' },
  { time: 4885, type: 'viseme', value: '@' },
  { time: 5047, type: 'viseme', value: 'sil' },
  { time: 5502, type: 'word', start: 76, end: 80, value: 'Need' },
  { time: 5502, type: 'viseme', value: 't' },
  { time: 5577, type: 'viseme', value: 'i' },
  { time: 5677, type: 'viseme', value: 't' },
  { time: 5727, type: 'word', start: 81, end: 85, value: 'cool' },
  { time: 5727, type: 'viseme', value: 'k' },
  { time: 5815, type: 'viseme', value: 'u' },
  { time: 5852, type: 'viseme', value: 't' },
  { time: 5965, type: 'word', start: 86, end: 91, value: 'techy' },
  { time: 5965, type: 'viseme', value: 't' },
  { time: 6065, type: 'viseme', value: 'E' },
  { time: 6127, type: 'viseme', value: 'k' },
  { time: 6202, type: 'viseme', value: 'i' },
  { time: 6252, type: 'word', start: 92, end: 97, value: 'stuff' },
  { time: 6252, type: 'viseme', value: 's' },
  { time: 6340, type: 'viseme', value: 't' },
  { time: 6390, type: 'viseme', value: 'E' },
  { time: 6502, type: 'viseme', value: 'f' },
  { time: 6690, type: 'viseme', value: 'sil' },
  { time: 7145, type: 'word', start: 99, end: 102, value: "I'm" },
  { time: 7145, type: 'viseme', value: 'a' },
  { time: 7232, type: 'viseme', value: 'p' },
  { time: 7282, type: 'word', start: 103, end: 107, value: 'your' },
  { time: 7282, type: 'viseme', value: 'i' },
  { time: 7370, type: 'viseme', value: 'E' },
  { time: 7457, type: 'word', start: 108, end: 110, value: 'IT' },
  { time: 7457, type: 'viseme', value: 'a' },
  { time: 7570, type: 'viseme', value: 't' },
  { time: 7670, type: 'viseme', value: 'i' },
  { time: 7757, type: 'word', start: 111, end: 114, value: 'guy' },
  { time: 7757, type: 'viseme', value: 'k' },
  { time: 7832, type: 'viseme', value: 'a' },
  { time: 8145, type: 'viseme', value: 'sil' },
  { time: 8600, type: 'word', start: 116, end: 119, value: 'How' },
  { time: 8600, type: 'viseme', value: 'k' },
  { time: 8662, type: 'viseme', value: 'a' },
  { time: 8712, type: 'word', start: 120, end: 123, value: 'can' },
  { time: 8712, type: 'viseme', value: 'k' },
  { time: 8775, type: 'viseme', value: 'a' },
  { time: 8812, type: 'viseme', value: 't' },
  { time: 8850, type: 'word', start: 124, end: 125, value: 'I' },
  { time: 8850, type: 'viseme', value: 'a' },
  { time: 8925, type: 'word', start: 126, end: 130, value: 'help' },
  { time: 8925, type: 'viseme', value: 'k' },
  { time: 8962, type: 'viseme', value: 'E' },
  { time: 9000, type: 'viseme', value: 't' },
  { time: 9075, type: 'viseme', value: 'p' },
  { time: 9137, type: 'word', start: 131, end: 134, value: 'you' },
  { time: 9137, type: 'viseme', value: 'i' },
  { time: 9187, type: 'viseme', value: 'u' },
  { time: 9225, type: 'word', start: 135, end: 140, value: 'today' },
  { time: 9225, type: 'viseme', value: 't' },
  { time: 9262, type: 'viseme', value: '@' },
  { time: 9300, type: 'viseme', value: 't' },
  { time: 9350, type: 'viseme', value: 'e' },
  { time: 9612, type: 'viseme', value: 'sil' },
]
