import { Phoneme } from '@/types'

export const initialPhonemesF: Phoneme[] = [
  { time: 125, type: 'word', start: 0, end: 2, value: 'Hi' },
  { time: 125, type: 'viseme', value: 'k' },
  { time: 200, type: 'viseme', value: 'a' },
  { time: 312, type: 'word', start: 3, end: 8, value: 'there' },
  { time: 312, type: 'viseme', value: 'T' },
  { time: 375, type: 'viseme', value: 'E' },
  { time: 500, type: 'viseme', value: 'r' },
  { time: 712, type: 'viseme', value: 'sil' },
  { time: 1255, type: 'word', start: 10, end: 12, value: 'My' },
  { time: 1255, type: 'viseme', value: 'p' },
  { time: 1367, type: 'viseme', value: 'a' },
  { time: 1430, type: 'word', start: 13, end: 17, value: 'name' },
  { time: 1430, type: 'viseme', value: 't' },
  { time: 1567, type: 'viseme', value: 'e' },
  { time: 1617, type: 'viseme', value: 'p' },
  { time: 1680, type: 'word', start: 18, end: 20, value: 'is' },
  { time: 1680, type: 'viseme', value: 'i' },
  { time: 1742, type: 'viseme', value: 's' },
  { time: 1830, type: 'word', start: 21, end: 25, value: 'Nova' },
  { time: 1830, type: 'viseme', value: 't' },
  { time: 1867, type: 'viseme', value: 'o' },
  { time: 1955, type: 'viseme', value: 'f' },
  { time: 2117, type: 'viseme', value: '@' },
  { time: 2267, type: 'viseme', value: 'sil' },
  { time: 2885, type: 'word', start: 27, end: 30, value: 'How' },
  { time: 2885, type: 'viseme', value: 'k' },
  { time: 2947, type: 'viseme', value: 'a' },
  { time: 3010, type: 'word', start: 31, end: 34, value: 'can' },
  { time: 3010, type: 'viseme', value: 'k' },
  { time: 3072, type: 'viseme', value: 'a' },
  { time: 3097, type: 'viseme', value: 't' },
  { time: 3172, type: 'word', start: 35, end: 36, value: 'I' },
  { time: 3172, type: 'viseme', value: 'a' },
  { time: 3260, type: 'word', start: 37, end: 41, value: 'help' },
  { time: 3260, type: 'viseme', value: 'k' },
  { time: 3322, type: 'viseme', value: 'E' },
  { time: 3385, type: 'viseme', value: 't' },
  { time: 3397, type: 'viseme', value: 'p' },
  { time: 3472, type: 'word', start: 42, end: 45, value: 'you' },
  { time: 3472, type: 'viseme', value: 'i' },
  { time: 3572, type: 'viseme', value: 'u' },
  { time: 3597, type: 'word', start: 46, end: 51, value: 'today' },
  { time: 3597, type: 'viseme', value: 't' },
  { time: 3697, type: 'viseme', value: '@' },
  { time: 3760, type: 'viseme', value: 't' },
  { time: 3822, type: 'viseme', value: 'e' },
  { time: 4135, type: 'viseme', value: 'sil' },
]
